services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USER=root
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=babacoiffure_db
      - Database_URI=mongodb://mongo:27017/saloon_db
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - db
      - mongo
    restart: unless-stopped

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=babacoiffure_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data: 
